In [1]:
import json
import numpy as np
import os

In [2]:
from pinn import *
from nn import NN

torch.set_default_dtype(torch.float32)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
def serialize_savelist(keys: list, values : list, filename):
    dict = {k: v for k, v in zip(keys, values)}
    filename = f"{filename}.json"
    with open(filename, 'w') as file:
        json.dump(dict, file)

In [4]:
# Parameters model
rho = 0.5
mu = 79300 # MPa
lam = 100000 # MPa

Lx = 0.2
Ly = 0.2
T = 0.2

x_domain = np.array([0.0, Lx])/Lx
y_domain = np.array([0.0, Ly])/Lx
t_domain = np.array([0.0, T])/T

# Parameters NN
epochs = 12000
n_train = 30
layers = 2
dim_hidden = 40
lr = 0.02
om_INITIAL = 2
om_BOUNDARY = 0.4

# Eventually save changed $NN_2$ parameters to pass to other script

In [5]:
par = [Lx, T, n_train, layers, dim_hidden]
keys = ['x', 't', 'n', 'n_layers', 'n_neurons']

serialize_savelist(keys, par, 'par')

In [6]:
pinn = PINN(layers, dim_hidden, act=nn.Tanh()).to(device)

loss_fn = Loss(
    x_domain,
    y_domain,
    t_domain,
    n_train,
    return_adim(x_domain, t_domain, rho, mu, lam),
    initial_conditions,
    om_INITIAL,
    om_BOUNDARY
)

# Import weights from pretrained model

In [7]:
filename_model = get_last_modified_file('in_model')
pretrained_model_dict = torch.load(filename_model, map_location=torch.device(device))

pretrained_model = NN(layers, dim_hidden, 2, 1)
pretrained_model.load_state_dict(pretrained_model_dict)

<All keys matched successfully>

In [8]:
for i in np.arange(len(pinn.middle_layers)):
    pinn_layer = pinn.middle_layers[i]
    pretrained_layer = pretrained_model.middle_layers[i]
    pinn.middle_layers[i].weight.data.copy_(pretrained_model.middle_layers[i].weight)
    pinn.middle_layers[i].bias.data.copy_(pretrained_model.middle_layers[i].bias)

# Train new network with pretrained weights and biases in middle layers

In [9]:
pinn_trained, loss_values = train_model(
    pinn, loss_fn=loss_fn, learning_rate=lr, max_epochs=epochs)

Folder '2024-04-27' already exists.


Training:   0%|          | 0/12000 [00:00<?, ?it/s]

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-5.8288e+11, -2.7312e+11, -2.0599e+11],
        [ 1.1265e+12,  6.6994e+11,  3.9808e+10],
        [ 1.4706e+12,  9.9825e+11,  3.7945e+11],
        [ 8.5162e+10,  3.4590e+10,  3.4695e+10],
        [-1.1241e+11, -5.2114e+10,  2.5819e+10],
        [-2.0214e+12, -1.0660e+12, -1.3579e+11],
        [-1.7294e+12, -8.1692e+11,  3.5926e+11],
        [-2.0623e+11, -9.2950e+10, -1.2432e+10],
        [ 1.3948e+12,  9.2302e+11,  3.6255e+11],
        [ 5.9268e+10,  1.9351e+10,  3.5547e+10],
        [ 6.1875e+10,  4.7277e+10,  7.6472e+10],
        [-7.6080e+11, -4.8484e+11,  8.3843e+10],
        [-1.0332e+11, -3.9405e+10, -6.7823e+10],
        [ 4.3742e+11,  1.9018e+11,  8.1403e+10],
        [-2.1921e+12, -1.1286e+12, -1.9030e+11],
        [ 3.9597e+11,  1.6737e+11,  1.5841e+10],
        [-1.5256e+12, -7.1127e+11,  1.8242e+11],
        [-4.4855e+11, -2.1496e+11, -1.0819e+11],
        [ 6.0196e+10,  4.2566e+09, -6.7

Loss: 188845924492682593809234657280.0000:   0%|          | 1/12000 [00:02<7:09:25,  2.15s/it]

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-5.1724e+11, -2.5025e+11, -1.7946e+11],
        [ 1.0499e+12,  6.7618e+11,  3.6168e+10],
        [ 1.1245e+12,  9.0446e+11,  2.2014e+11],
        [ 7.1424e+10,  2.8774e+10,  2.8973e+10],
        [-1.2265e+11, -5.8790e+10,  1.8488e+10],
        [-1.8937e+12, -1.0492e+12, -1.0977e+11],
        [-1.6208e+12, -7.9500e+11,  4.0902e+11],
        [-1.9542e+11, -9.0586e+10, -1.0566e+10],
        [ 1.1598e+12,  8.5780e+11,  2.6073e+11],
        [ 8.0573e+10,  2.8369e+10,  4.8975e+10],
        [ 7.7640e+10,  5.8624e+10,  9.1556e+10],
        [-5.9890e+11, -4.5490e+11,  1.5741e+11],
        [-8.9587e+10, -3.0600e+10, -6.2548e+10],
        [ 4.3486e+11,  1.8921e+11,  8.9027e+10],
        [-2.0026e+12, -1.0728e+12, -1.2262e+11],
        [ 3.7983e+11,  1.6008e+11,  8.8472e+09],
        [-1.3923e+12, -6.6820e+11,  2.3392e+11],
        [-4.2511e+11, -2.1133e+11, -1.0775e+11],
        [ 8.2167e+10,  6.7719e+09,  1.0

Loss: 1888459303956406973962911744.0000:   0%|          | 2/12000 [00:03<5:23:45,  1.62s/it]  

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-4.7664e+11, -2.3498e+11, -1.6098e+11],
        [ 1.0181e+12,  6.8767e+11,  4.3943e+10],
        [ 9.1277e+11,  8.5148e+11,  1.1501e+11],
        [ 6.2529e+10,  2.4970e+10,  2.4827e+10],
        [-1.3506e+11, -6.6842e+10,  8.6126e+09],
        [-1.8538e+12, -1.0554e+12, -1.1741e+11],
        [-1.6322e+12, -8.2939e+11,  3.8238e+11],
        [-1.9073e+11, -9.0494e+10, -1.1051e+10],
        [ 1.0273e+12,  8.2494e+11,  2.0269e+11],
        [ 9.3070e+10,  3.2533e+10,  5.7193e+10],
        [ 8.0697e+10,  5.9874e+10,  9.5862e+10],
        [-5.1634e+11, -4.5004e+11,  1.9291e+11],
        [-7.8955e+10, -2.2018e+10, -5.5679e+10],
        [ 4.3888e+11,  1.9011e+11,  9.7972e+10],
        [-1.9299e+12, -1.0602e+12, -1.0717e+11],
        [ 3.8130e+11,  1.6114e+11,  1.2009e+10],
        [-1.3641e+12, -6.6726e+11,  2.3328e+11],
        [-4.1277e+11, -2.0870e+11, -1.0829e+11],
        [ 9.9556e+10,  9.7081e+09,  2.0

Loss: 18884591379357103105769472.0000:   0%|          | 3/12000 [00:04<4:23:28,  1.32s/it]  

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-4.4885e+11, -2.2366e+11, -1.4692e+11],
        [ 1.0049e+12,  6.9855e+11,  5.4528e+10],
        [ 7.8008e+11,  8.2472e+11,  4.8951e+10],
        [ 5.6297e+10,  2.2317e+10,  2.1745e+10],
        [-1.4669e+11, -7.4357e+10, -9.7793e+08],
        [-1.8463e+12, -1.0644e+12, -1.3184e+11],
        [-1.6873e+12, -8.8017e+11,  3.2964e+11],
        [-1.8868e+11, -9.1156e+10, -1.2411e+10],
        [ 9.4911e+11,  8.0925e+11,  1.7029e+11],
        [ 9.9993e+10,  3.3634e+10,  6.1435e+10],
        [ 7.7576e+10,  5.6270e+10,  9.4348e+10],
        [-4.7632e+11, -4.5815e+11,  2.0580e+11],
        [-6.9715e+10, -1.3537e+10, -4.7835e+10],
        [ 4.4294e+11,  1.8993e+11,  1.0454e+11],
        [-1.9048e+12, -1.0611e+12, -1.0925e+11],
        [ 3.8806e+11,  1.6404e+11,  1.7362e+10],
        [-1.3734e+12, -6.7704e+11,  2.1791e+11],
        [-4.0437e+11, -2.0549e+11, -1.0779e+11],
        [ 1.1255e+11,  1.1684e+10,  2.7

Loss: 188845912352419150299136.0000:   0%|          | 4/12000 [00:05<4:00:19,  1.20s/it]  

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-4.2817e+11, -2.1429e+11, -1.3534e+11],
        [ 9.9949e+11,  7.0658e+11,  6.4465e+10],
        [ 6.9654e+11,  8.1405e+11,  9.7472e+09],
        [ 5.1686e+10,  2.0343e+10,  1.9400e+10],
        [-1.5687e+11, -8.0882e+10, -9.5423e+09],
        [-1.8492e+12, -1.0689e+12, -1.4330e+11],
        [-1.7571e+12, -9.3253e+11,  2.7025e+11],
        [-1.8790e+11, -9.1998e+10, -1.4080e+10],
        [ 9.0196e+11,  8.0249e+11,  1.5334e+11],
        [ 1.0314e+11,  3.2694e+10,  6.2805e+10],
        [ 7.1021e+10,  5.0055e+10,  8.9433e+10],
        [-4.6086e+11, -4.7288e+11,  2.0506e+11],
        [-6.1029e+10, -4.9845e+09, -3.9203e+10],
        [ 4.4523e+11,  1.8797e+11,  1.0816e+11],
        [-1.8989e+12, -1.0636e+12, -1.1494e+11],
        [ 3.9565e+11,  1.6647e+11,  2.2152e+10],
        [-1.3947e+12, -6.8649e+11,  2.0161e+11],
        [-3.9720e+11, -2.0120e+11, -1.0578e+11],
        [ 1.2194e+11,  1.2505e+10,  3.3

Loss: 1888458965898204545024.0000:   0%|          | 5/12000 [00:06<4:19:26,  1.30s/it]  

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-4.1229e+11, -2.0626e+11, -1.2553e+11],
        [ 9.9754e+11,  7.1144e+11,  7.2711e+10],
        [ 6.4646e+11,  8.1341e+11, -1.0317e+10],
        [ 4.8227e+10,  1.8858e+10,  1.7611e+10],
        [-1.6541e+11, -8.6303e+10, -1.6849e+10],
        [-1.8543e+12, -1.0675e+12, -1.4923e+11],
        [-1.8283e+12, -9.8027e+11,  2.1244e+11],
        [-1.8785e+11, -9.2861e+10, -1.5859e+10],
        [ 8.7481e+11,  8.0074e+11,  1.4641e+11],
        [ 1.0375e+11,  3.0497e+10,  6.2144e+10],
        [ 6.2804e+10,  4.2644e+10,  8.2616e+10],
        [-4.6044e+11, -4.9043e+11,  1.9579e+11],
        [-5.2708e+10,  3.4989e+09, -3.0100e+10],
        [ 4.4566e+11,  1.8456e+11,  1.0918e+11],
        [-1.9006e+12, -1.0637e+12, -1.1932e+11],
        [ 4.0242e+11,  1.6779e+11,  2.5549e+10],
        [-1.4177e+12, -6.9188e+11,  1.8902e+11],
        [-3.9059e+11, -1.9613e+11, -1.0253e+11],
        [ 1.2843e+11,  1.2381e+10,  3.6

Loss: 18884813695471321088.0000:   0%|          | 6/12000 [00:07<3:51:22,  1.16s/it]  

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-3.9932e+11, -1.9890e+11, -1.1677e+11],
        [ 9.9645e+11,  7.1308e+11,  7.8820e+10],
        [ 6.1815e+11,  8.1845e+11, -1.7454e+10],
        [ 4.5533e+10,  1.7676e+10,  1.6213e+10],
        [-1.7247e+11, -9.0720e+10, -2.2988e+10],
        [-1.8571e+12, -1.0599e+12, -1.4881e+11],
        [-1.8951e+12, -1.0212e+12,  1.5967e+11],
        [-1.8813e+11, -9.3603e+10, -1.7605e+10],
        [ 8.5978e+11,  8.0123e+11,  1.4561e+11],
        [ 1.0260e+11,  2.7478e+10,  6.0060e+10],
        [ 5.3734e+10,  3.4683e+10,  7.4716e+10],
        [-4.6891e+11, -5.0875e+11,  1.8147e+11],
        [-4.4555e+10,  1.1930e+10, -2.0643e+10],
        [ 4.4426e+11,  1.7987e+11,  1.0802e+11],
        [-1.9033e+12, -1.0596e+12, -1.1998e+11],
        [ 4.0771e+11,  1.6779e+11,  2.7318e+10],
        [-1.4377e+12, -6.9213e+11,  1.8187e+11],
        [-3.8398e+11, -1.9032e+11, -9.8171e+10],
        [ 1.3266e+11,  1.1478e+10,  3.8

Loss: 188950506297622528.0000:   0%|          | 7/12000 [00:08<3:46:41,  1.13s/it]  

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-3.8854e+11, -1.9212e+11, -1.0888e+11],
        [ 9.9530e+11,  7.1199e+11,  8.2907e+10],
        [ 6.0479e+11,  8.2648e+11, -1.5703e+10],
        [ 4.3424e+10,  1.6731e+10,  1.5120e+10],
        [-1.7815e+11, -9.4226e+10, -2.8034e+10],
        [-1.8566e+12, -1.0470e+12, -1.4282e+11],
        [-1.9545e+12, -1.0546e+12,  1.1349e+11],
        [-1.8860e+11, -9.4221e+10, -1.9277e+10],
        [ 8.5272e+11,  8.0265e+11,  1.4865e+11],
        [ 1.0033e+11,  2.4040e+10,  5.7046e+10],
        [ 4.4542e+10,  2.6749e+10,  6.6406e+10],
        [-4.8244e+11, -5.2640e+11,  1.6439e+11],
        [-3.6641e+10,  2.0134e+10, -1.1110e+10],
        [ 4.4145e+11,  1.7437e+11,  1.0523e+11],
        [-1.9047e+12, -1.0514e+12, -1.1669e+11],
        [ 4.1140e+11,  1.6662e+11,  2.7594e+10],
        [-1.4529e+12, -6.8746e+11,  1.8009e+11],
        [-3.7743e+11, -1.8412e+11, -9.3088e+10],
        [ 1.3515e+11,  1.0043e+10,  3.8

Loss: 2073656515624960.0000:   0%|          | 8/12000 [00:09<3:23:07,  1.02s/it]  

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-3.7913e+11, -1.8562e+11, -1.0155e+11],
        [ 9.9339e+11,  7.0847e+11,  8.5095e+10],
        [ 6.0110e+11,  8.3570e+11, -8.1493e+09],
        [ 4.1713e+10,  1.5930e+10,  1.4242e+10],
        [-1.8268e+11, -9.6969e+10, -3.2166e+10],
        [-1.8521e+12, -1.0296e+12, -1.3188e+11],
        [-2.0060e+12, -1.0809e+12,  7.3902e+10],
        [-1.8910e+11, -9.4664e+10, -2.0827e+10],
        [ 8.5037e+11,  8.0398e+11,  1.5388e+11],
        [ 9.7276e+10,  2.0357e+10,  5.3401e+10],
        [ 3.5451e+10,  1.9007e+10,  5.7961e+10],
        [-4.9866e+11, -5.4280e+11,  1.4595e+11],
        [-2.8909e+10,  2.8120e+10, -1.5545e+09],
        [ 4.3746e+11,  1.6821e+11,  1.0115e+11],
        [-1.9033e+12, -1.0392e+12, -1.0939e+11],
        [ 4.1355e+11,  1.6439e+11,  2.6545e+10],
        [-1.4629e+12, -6.7845e+11,  1.8323e+11],
        [-3.7077e+11, -1.7759e+11, -8.7414e+10],
        [ 1.3630e+11,  8.1997e+09,  3.8

Loss: 143683819143168.0000:   0%|          | 9/12000 [00:10<3:02:27,  1.10it/s] 

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-3.7084e+11, -1.7945e+11, -9.4744e+10],
        [ 9.9067e+11,  7.0305e+11,  8.5705e+10],
        [ 6.0383e+11,  8.4497e+11,  3.1127e+09],
        [ 4.0318e+10,  1.5248e+10,  1.3534e+10],
        [-1.8622e+11, -9.9058e+10, -3.5496e+10],
        [-1.8442e+12, -1.0089e+12, -1.1720e+11],
        [-2.0495e+12, -1.1005e+12,  4.0721e+10],
        [-1.8959e+11, -9.4960e+10, -2.2253e+10],
        [ 8.5099e+11,  8.0484e+11,  1.6029e+11],
        [ 9.3791e+10,  1.6639e+10,  4.9408e+10],
        [ 2.6780e+10,  1.1702e+10,  4.9699e+10],
        [-5.1591e+11, -5.5746e+11,  1.2720e+11],
        [-2.1465e+10,  3.5753e+10,  7.8150e+09],
        [ 4.3264e+11,  1.6173e+11,  9.6221e+10],
        [-1.8989e+12, -1.0237e+12, -9.8848e+10],
        [ 4.1437e+11,  1.6136e+11,  2.4455e+10],
        [-1.4680e+12, -6.6598e+11,  1.9038e+11],
        [-3.6416e+11, -1.7097e+11, -8.1433e+10],
        [ 1.3646e+11,  6.1205e+09,  3.7

Loss: 508741292130304.0000:   0%|          | 10/12000 [00:11<3:06:58,  1.07it/s]

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-3.6327e+11, -1.7345e+11, -8.8287e+10],
        [ 9.8698e+11,  6.9600e+11,  8.4928e+10],
        [ 6.1054e+11,  8.5359e+11,  1.6607e+10],
        [ 3.9140e+10,  1.4637e+10,  1.2946e+10],
        [-1.8893e+11, -1.0061e+11, -3.8173e+10],
        [-1.8329e+12, -9.8546e+11, -9.9411e+10],
        [-2.0855e+12, -1.1143e+12,  1.3228e+10],
        [-1.9001e+11, -9.5090e+10, -2.3540e+10],
        [ 8.5316e+11,  8.0489e+11,  1.6720e+11],
        [ 9.0026e+10,  1.2939e+10,  4.5197e+10],
        [ 1.8545e+10,  4.8313e+09,  4.1681e+10],
        [-5.3329e+11, -5.7034e+11,  1.0867e+11],
        [-1.4276e+10,  4.3057e+10,  1.6997e+10],
        [ 4.2715e+11,  1.5501e+11,  9.0631e+10],
        [-1.8914e+12, -1.0055e+12, -8.5407e+10],
        [ 4.1403e+11,  1.5767e+11,  2.1500e+10],
        [-1.4689e+12, -6.5075e+11,  2.0086e+11],
        [-3.5754e+11, -1.6429e+11, -7.5208e+10],
        [ 1.3585e+11,  3.8711e+09,  3.5

Loss: 177405956194304.0000:   0%|          | 11/12000 [00:12<3:07:56,  1.06it/s]

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-3.5636e+11, -1.6768e+11, -8.2202e+10],
        [ 9.8247e+11,  6.8774e+11,  8.3061e+10],
        [ 6.1964e+11,  8.6114e+11,  3.1256e+10],
        [ 3.8140e+10,  1.4087e+10,  1.2454e+10],
        [-1.9095e+11, -1.0171e+11, -4.0291e+10],
        [-1.8191e+12, -9.6037e+11, -7.9529e+10],
        [-2.1147e+12, -1.1231e+12, -9.1463e+09],
        [-1.9036e+11, -9.5081e+10, -2.4697e+10],
        [ 8.5615e+11,  8.0406e+11,  1.7415e+11],
        [ 8.6162e+10,  9.3659e+09,  4.0926e+10],
        [ 1.0881e+10, -1.5060e+09,  3.4056e+10],
        [-5.5010e+11, -5.8133e+11,  9.0829e+10],
        [-7.4255e+09,  4.9948e+10,  2.5855e+10],
        [ 4.2127e+11,  1.4825e+11,  8.4663e+10],
        [-1.8814e+12, -9.8526e+11, -6.9886e+10],
        [ 4.1277e+11,  1.5353e+11,  1.7927e+10],
        [-1.4661e+12, -6.3356e+11,  2.1377e+11],
        [-3.5103e+11, -1.5769e+11, -6.8930e+10],
        [ 1.3469e+11,  1.5591e+09,  3.3

Loss: 385653334343680.0000:   0%|          | 12/12000 [00:13<3:07:26,  1.07it/s]

Parameter name: layer_in.weight
Parameter shape: torch.Size([40, 3])
Gradient:
tensor([[-3.4986e+11, -1.6204e+11, -7.6370e+10],
        [ 9.7716e+11,  6.7844e+11,  8.0249e+10],
        [ 6.3002e+11,  8.6740e+11,  4.6392e+10],
        [ 3.7263e+10,  1.3570e+10,  1.2030e+10],
        [-1.9239e+11, -1.0243e+11, -4.1954e+10],
        [-1.8032e+12, -9.3393e+11, -5.7961e+10],
        [-2.1379e+12, -1.1277e+12, -2.7126e+10],
        [-1.9060e+11, -9.4927e+10, -2.5722e+10],
        [ 8.5935e+11,  8.0228e+11,  1.8088e+11],
        [ 8.2255e+10,  5.9215e+09,  3.6641e+10],
        [ 3.7337e+09, -7.3652e+09,  2.6801e+10],
        [-5.6607e+11, -5.9057e+11,  7.3811e+10],
        [-8.8075e+08,  5.6461e+10,  3.4419e+10],
        [ 4.1505e+11,  1.4149e+11,  7.8411e+10],
        [-1.8691e+12, -9.6338e+11, -5.2584e+10],
        [ 4.1074e+11,  1.4904e+11,  1.3855e+10],
        [-1.4604e+12, -6.1487e+11,  2.2865e+11],
        [-3.4458e+11, -1.5118e+11, -6.2610e+10],
        [ 1.3311e+11, -7.8796e+08,  3.1

Loss: 202335506661376.0000:   0%|          | 13/12000 [00:14<3:18:09,  1.01it/s]

KeyboardInterrupt: 

In [ ]:
current_time = get_current_time(fmt="%H:%M")

folder = 'model'
model_name = f'{lr}_{epochs}_{dim_hidden}_{current_time}.pth'
model_path = os.path.join(folder, model_name)
os.makedirs(folder, exist_ok=True)

torch.save(pinn_trained.state_dict(), model_path)

In [ ]:
from plots import plot_initial_conditions, plot_solution

x, y, _ = get_initial_points(x_domain, y_domain, t_domain, n_train)
t_value = 0.0
t = torch.full_like(x, t_value)
x = x.to(device)
y = y.to(device)
t = t.to(device)
z = f(pinn, x ,y, t)
ux_0, uy_0 = initial_conditions(x, y, Lx, i = 1)
z_0 = torch.cat((ux_0, uy_0), dim=1)

plot_initial_conditions(z_0, y, x, 'Initial conditions - analytical', n_train, from_pinn = 0)
plot_initial_conditions(z, y, x, 'Initial conditions - NN', n_train)

In [ ]:
from IPython.display import HTML

x, y, t = get_interior_points(x_domain, y_domain, t_domain, n_train)
animation = plot_solution(pinn, x, y, t, n_train)
HTML(animation.to_jshtml())

# To be added
- ~separate loss in more bars to see how the various loss term come to zero~
- see if some quadrature rule has been implemented
- scheme of weights initialization in order to automatically satisfy initial conditions
- plots (in progress)
- NN operators (to generalize results)
- try to implement function that allows that satisfy initial conditions?

# To be fully understood
- reshape when plotting (also different number of points allowed?)
- ~not consistent initial conditions~ (between $u_x$ and $u_y$)?